name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  pull_request:
    branches:
      - master
    paths:
      - "Dockerfile"
      - ".github/workflows/build.yml"
  # workflow_run:
  #   workflows: [Build Docker Image]
  #   types:
  #     - completed

env:
  # https://github.com/grafana/loki/releases
  LOKI_VERSION: 2.5.0
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # - name: Log in to the GitHub Container registry
      #   uses: docker/login-action@v2
      #   with:
      #     registry: ${{ env.REGISTRY }}
      #     username: ${{ github.actor }}
      #     password: ${{ secrets.GITHUB_TOKEN }}

      # - name: Extract metadata (tags, labels) for Docker
      #   id: meta
      #   uses: docker/metadata-action@v4
      #   with:
      #     images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      #     flavor: |
      #       latest=true

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v2

      # - name: Build and Push Docker Image
      #   uses: docker/build-push-action@v3
      #   with:
      #     context: .
      #     # platforms: linux/amd64,linux/arm64
      #     platforms: linux/arm64
      #     push: true
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}

      - name: Build Release
        run: |
          # curl -sfLO https://github.com/grafana/loki/archive/refs/tags/v$LOKI_VERSION.zip
          # unzip -q v$LOKI_VERSION.zip
          # ls -alh

          mkdir -p $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/
          touch $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/promtail-linux-arm64

          # docker run --rm \
          #   --platform linux/arm64 \
          #   -v $PWD/loki-$LOKI_VERSION:/usr/src/myapp \
          #   -w /usr/src/myapp \
          #   ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} \
          #   make BUILD_IN_CONTAINER=false promtail

          # cp \
          #   $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/promtail \
          #   $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/promtail-linux-arm64

      - name: Check
        run: |
          pwd
          ls -alh
          ls -alh $PWD/loki-$LOKI_VERSION
          ls -alh $PWD/loki-$LOKI_VERSION/clients/cmd/promtail

      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   with:
      #     name: $LOKI_VERSION
      #     files: |
      #       $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/promtail-linux-arm64

      - name: Release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: $PWD/loki-$LOKI_VERSION/clients/cmd/promtail/promtail-linux-arm64
          asset_name: promtail-linux-arm64
          tag: ${{ github.ref }}
          overwrite: true
